---
services:
  ansible:
    image: ghcr.io/netresearch/ansible_role_client_base:latest
    build: .
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
    volumes:
      - ./example/site.yml:/site.yml
    command: ansible-playbook /site.yml -i <ip>, --ask-pass --ask-become-pass
    stdin_open: true
    tty: true
