---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Override flatpak_apps for CI - minimal set reduces disk usage.
    # Full app list would consume too much space in CI runners.
    flatpak_apps:
      - {id: "org.gnome.Calculator", name: "GNOME Calculator"}
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: ansible_role_client_base
