---
dependency:
  name: galaxy
driver:
  name: docker
  config_options:
    defaults:
      remote_user: ubuntu
      interpreter_python: /opt/ansible-venv/bin/python

platforms:
  - name: instance-ubuntu22
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    privileged: true
    pre_build_image: true
    cgroupns: host
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: instance-ubuntu24
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    privileged: true
    pre_build_image: true
    cgroupns: host
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  become: true
  options:
    diff: true
lint:
  yamllint
scenario:
  name: default
verifier:
  name: ansible
