---
# https://github.com/ansible/ansible/issues/19681#issuecomment-450425779
# do not fail while testing. see link above
- name: "Hostname | Set hostname"
  ansible.builtin.hostname:
    name: "{{ hostname }}.{{ domainname }}"
  when: >
    ansible_facts.virtualization_type not in
    [
      'docker',
      'container',
      'containerd'
    ]

- name: "Hostname | Add to /etc/hosts"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    insertafter: '^127\.0\.0\.1[ \t]*'
    line: '127.0.1.1  {{ hostname }}.{{ domainname }} {{ hostname }}'
    state: present
    unsafe_writes: "{{ lookup('env', 'MOLECULE_FILE') is not none }}"
